version: '2'
services:
  web:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file: production.env
  redis:
    image: redis
  db:
    image: mysql
    env_file: mysql/mysql.env
    volumes:
      - ./mysql:/etc/mysql/conf.d
    ports:
      - "3333:3306"